name: keepapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  giffy_dialog:
  rxdart: ^0.23.1
  flutter_colorpicker: ^0.3.2
  fluttertoast: ^4.0.1
  tinycolor: ^1.0.2
  cupertino_icons: ^0.1.3
  linear_gradient: ^0.1.12
  url_launcher: ^5.4.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  provider: ^4.1.1
  intl: ^0.16.1
  flutter_svg: ^0.17.4
  cross_local_storage: ^1.1.1
  percent_indicator: ^2.1.3

  datetime_picker_formfield: ^1.0.0
  path_provider: ^1.4.0
  chips_choice: ^1.2.0
  dio: ^3.0.9
  overlay_support: ^1.0.4
  firebase_core: ^0.4.4+3

  flutter_bloc: ^4.0.0
  equatable: ^1.0.0
  meta: ^1.1.6
  font_awesome_flutter: ^8.4.0
  nepninja: ^0.0.4
  json_annotation: ^2.0.0
  vector_math: ^2.0.7
  firebase: ^7.3.0
  firebase_auth_web:
  flutter_screenutil: ^0.5.2
  line_icons:
  image_picker_web: any
  googleapis_auth:
  flutter_phoenix: ^0.1.0
  #js: ^0.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: ^2.10.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
        - asset: assets/fonts/Lato-MediumItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-B.ttf
        - asset: assets/fonts/Ubuntu-BI.ttf
        - asset: assets/fonts/Ubuntu-MI.ttf
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Blaster
      fonts:
        - asset: assets/fonts/Blaster.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    
        